# Generated by Django 3.1.4 on 2022-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0008_auto_20211207_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
